//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QvNLogicConnector {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QvNLogicConnector.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AMA (000).
        /// </summary>
        internal static string AMA {
            get {
                return ResourceManager.GetString("AMA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audience.
        /// </summary>
        internal static string Audience {
            get {
                return ResourceManager.GetString("Audience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cumulative Reach.
        /// </summary>
        internal static string CumeReach {
            get {
                return ResourceManager.GetString("CumeReach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cumulative Reach %.
        /// </summary>
        internal static string CumeReachPercent {
            get {
                return ResourceManager.GetString("CumeReachPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily Reach.
        /// </summary>
        internal static string DailyReach {
            get {
                return ResourceManager.GetString("DailyReach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily Reach %.
        /// </summary>
        internal static string DailyReachPercent {
            get {
                return ResourceManager.GetString("DailyReachPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daypart.
        /// </summary>
        internal static string Daypart {
            get {
                return ResourceManager.GetString("Daypart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        internal static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Time.
        /// </summary>
        internal static string EndTime {
            get {
                return ResourceManager.GetString("EndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Airing.
        /// </summary>
        internal static string FirstAiring {
            get {
                return ResourceManager.GetString("FirstAiring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimated Frequency.
        /// </summary>
        internal static string Frequency {
            get {
                return ResourceManager.GetString("Frequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimated Impressions.
        /// </summary>
        internal static string Impressions {
            get {
                return ResourceManager.GetString("Impressions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Airing.
        /// </summary>
        internal static string LastAiring {
            get {
                return ResourceManager.GetString("LastAiring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Market.
        /// </summary>
        internal static string Market {
            get {
                return ResourceManager.GetString("Market", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Aired.
        /// </summary>
        internal static string NumAired {
            get {
                return ResourceManager.GetString("NumAired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program Name.
        /// </summary>
        internal static string ProgramName {
            get {
                return ResourceManager.GetString("ProgramName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating %.
        /// </summary>
        internal static string Rating {
            get {
                return ResourceManager.GetString("Rating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimated Reach %.
        /// </summary>
        internal static string ReachPercent {
            get {
                return ResourceManager.GetString("ReachPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share %.
        /// </summary>
        internal static string Share {
            get {
                return ResourceManager.GetString("Share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Time.
        /// </summary>
        internal static string StartTime {
            get {
                return ResourceManager.GetString("StartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Station Name.
        /// </summary>
        internal static string StationName {
            get {
                return ResourceManager.GetString("StationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekdays.
        /// </summary>
        internal static string Weekdays {
            get {
                return ResourceManager.GetString("Weekdays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekly Reach.
        /// </summary>
        internal static string WeeklyReach {
            get {
                return ResourceManager.GetString("WeeklyReach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekly Reach %.
        /// </summary>
        internal static string WeeklyReachPercent {
            get {
                return ResourceManager.GetString("WeeklyReachPercent", resourceCulture);
            }
        }
    }
}
